server:
  port: 8081

spring:
  application:
    name: consumer
  cloud:
    servicecomb:
      discovery:
        address: http://127.0.0.1:30100
servicecomb:
  matchGroup:
    demo-rateLimiting: |
      matches:
        - apiPath:
            exact: "/hello"
          name: xx
    demo-retry: |
      matches:
        - apiPath:
            exact: "/retry"
          name: xx
    demo-circuitBreaker: |
      matches:
        - apiPath:
            exact: "/circuitBreaker"
          name: xx
    demo-bulkhead: |
      matches:
        - apiPath:
            exact: "/bulkhead"
          name: xx
  rateLimiting:
    demo-rateLimiting: |
      rules:
        match: xx
      rate: 1
      name: xx
  retry:
    demo-retry: |
      rules:
        match: xx
      maxAttempts: 3
      name: xx
  circuitBreaker:
    demo-circuitBreaker: |
      rules:
        match: xx
      minimumNumberOfCalls: 2
      slidingWindowSize: 2
      name: xx
  bulkhead:
    demo-bulkhead: |
      rules:
        match: xx
      maxConcurrentCalls: 1
      name: xx